### ISSUE TITLE
[RFE] Support Tofu/Terraform Workspaces

### ISSUE THREAD

**Issue by git-ival** [rancher/dartboard#20]
Various dartboard modules generate files (aka stateful artifacts) that are stored on the dartboard-runner machine. If using tofu/terraform workspaces, these files will be overwritten on a `dartboard deploy` or `dartboard apply`.

Suggestion: Ensure all modules that generate files place them in a directory prefixed with the terraform workspace name. ex: `${terraform.workspace}_config`

- [ ] Store all stateful artifacts in a directory named as `${terraform.workspace}_config`
- [ ] Should be able to set the terraform workspace that should be used in dart files
  - If the workspace doesn't exist, it should be created

**Comment by moio** [comment]
At the moment all files should be created inside of the `main/$backend` directory, which kind of acts as a "workspace"

I am totally open to making that parametric so that it can point elsewhere

**Comment by git-ival** [comment]
🤔 In my experience files are just stored in the "main" modules `${path.root}/config/` directory.

**Comment by moio** [comment]
OK, so I misunderstood what "workspace" meant

reading https://opentofu.org/docs/cli/workspaces/ clarified the concept for me

I am totally OK with this change 👍
